# Header
menu:
  Home: /
  Archives: /archives
  Github:
    url: https://github.com/mrtraan
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: 

# URL of the Home page image
index_cover: http://images.mrtraan.love/footer_lodyas.png

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: blog-j3x2huefot
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-85332538-1

# Addthis ID
addthis:

# Social Accounts
twitter_url: https://twitter.com/nathan_grasset
twitter_handle:
facebook_url:
github_url:
gitlab_url:
linkedin_url:
mailto:
